/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package scaffolds

import (
	"fmt"
	"strings"
)

// APIData holds the data required to render API scaffold templates.
type APIData struct {
	// Group is the API group (e.g. "apps").
	Group string
	// Version is the API version (e.g. "v1").
	Version string
	// Kind is the resource kind (e.g. "MyApp").
	Kind string
	// Namespaced indicates whether the resource is namespace-scoped.
	Namespaced bool
	// PluginKey is the full plugin identifier.
	PluginKey string
	// PluginVersion is the plugin semver string.
	PluginVersion string
}

// KindLower returns the lowercase Kind.
func (d APIData) KindLower() string { return strings.ToLower(d.Kind) }

// Scope returns "Namespaced" or "Cluster" based on Namespaced.
func (d APIData) Scope() string {
	if d.Namespaced {
		return "Namespaced"
	}
	return "Cluster"
}

// RenderAPIPlatform renders platform-zone API templates (always overwritten).
func RenderAPIPlatform(data APIData) (map[string]string, error) {
	rawMap := map[string]string{
		fmt.Sprintf("internal/platform/reconciler/%s_reconciler.go", data.KindLower()): platformReconcilerTmpl,
		"internal/platform/reconciler/hooks.go": platformHooksTmpl,
		"internal/platform/reconciler/noop.go":  platformNoopTmpl,
	}
	return renderMap(rawMap, data)
}

// RenderAPIApp renders app-zone API stub templates (create-only).
func RenderAPIApp(data APIData) (map[string]string, error) {
	rawMap := map[string]string{
		fmt.Sprintf("internal/app/%s/hooks.go", data.KindLower()):      appHooksTmpl,
		fmt.Sprintf("internal/app/%s/hooks_test.go", data.KindLower()): appHooksTestTmpl,
	}
	return renderMap(rawMap, data)
}

// platformReconcilerTmpl is the generated reconciler skeleton.
// It depends on ReconcileHooks (defined in hooks.go) and delegates all
// business logic to the user's app-layer implementation.
const platformReconcilerTmpl = `// Code generated by {{ .PluginKey }} ({{ .PluginVersion }}). DO NOT EDIT.
// Regenerate: kubebuilder edit --plugins {{ .PluginKey }} --regenerate
package reconciler

import (
	"context"

	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"
)

// {{ .Kind }}Reconciler reconciles {{ .Kind }} objects.
// It delegates all business logic to the ReconcileHooks implementation
// provided at construction time.
//
// Implement ReconcileHooks in internal/app/{{ .KindLower }}/hooks.go.
type {{ .Kind }}Reconciler struct {
	client client.Client
	hooks  ReconcileHooks
}

// New{{ .Kind }}Reconciler creates a reconciler wired to the provided hooks.
func New{{ .Kind }}Reconciler(c client.Client, hooks ReconcileHooks) *{{ .Kind }}Reconciler {
	return &{{ .Kind }}Reconciler{client: c, hooks: hooks}
}

// Reconcile is the main reconciliation loop. It is called by controller-runtime
// whenever a {{ .Kind }} object (or a watched dependent) changes.
func (r *{{ .Kind }}Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := log.FromContext(ctx)
	log.Info("Reconciling {{ .Kind }}", "name", req.Name, "namespace", req.Namespace)

	if err := r.hooks.BeforeReconcile(ctx, req); err != nil {
		return r.hooks.OnError(ctx, nil, err)
	}

	// TODO: replace client.Object with your concrete API type once generated.
	// Example: obj := &appsv1.{{ .Kind }}{}
	var obj client.Object
	if err := r.client.Get(ctx, req.NamespacedName, obj); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	result, err := r.hooks.Reconcile(ctx, obj)
	if err != nil {
		return r.hooks.OnError(ctx, obj, err)
	}

	return r.hooks.AfterReconcile(ctx, obj, result)
}

// SetupWithManager registers the {{ .Kind }}Reconciler with the controller manager.
func (r *{{ .Kind }}Reconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		// TODO: replace with your concrete API type once generated.
		// For(..., &appsv1.{{ .Kind }}{}).
		Complete(r)
}
`

// platformHooksTmpl defines the ReconcileHooks interface in the platform layer.
const platformHooksTmpl = `// Code generated by {{ .PluginKey }} ({{ .PluginVersion }}). DO NOT EDIT.
// Regenerate: kubebuilder edit --plugins {{ .PluginKey }} --regenerate
package reconciler

import (
	"context"

	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// ReconcileHooks defines the extension points for {{ .Kind }} reconciliation.
//
// Implement this interface in internal/app/{{ .KindLower }}/hooks.go.
// The platform reconciler calls these methods in order on each reconcile cycle.
//
// For a no-op starting point, embed NoopHooks in your implementation.
type ReconcileHooks interface {
	// BeforeReconcile is called before the object is fetched from the API server.
	// Use it for pre-flight checks (e.g. leader election guards, rate limiting).
	// Return a non-nil error to skip the main Reconcile step and call OnError.
	BeforeReconcile(ctx context.Context, req reconcile.Request) error

	// Reconcile contains the main business logic for {{ .Kind }}.
	// obj is the current {{ .Kind }} object fetched from the API server.
	// Return (ctrl.Result{}, nil) on success.
	// Return (ctrl.Result{RequeueAfter: d}, nil) to requeue after a delay.
	Reconcile(ctx context.Context, obj client.Object) (ctrl.Result, error)

	// AfterReconcile is called after a successful Reconcile.
	// Use it to update status conditions, emit events, or finalise the cycle.
	AfterReconcile(ctx context.Context, obj client.Object, result ctrl.Result) (ctrl.Result, error)

	// OnError is called when BeforeReconcile or Reconcile returns a non-nil error.
	// Use it to update status conditions and decide whether to requeue.
	// Returning (ctrl.Result{}, nil) suppresses the error from controller-runtime
	// (no exponential backoff). Returning (ctrl.Result{}, err) enables backoff.
	OnError(ctx context.Context, obj client.Object, err error) (ctrl.Result, error)
}
`

// platformNoopTmpl provides default no-op implementations for all hook methods.
const platformNoopTmpl = `// Code generated by {{ .PluginKey }} ({{ .PluginVersion }}). DO NOT EDIT.
// Regenerate: kubebuilder edit --plugins {{ .PluginKey }} --regenerate
package reconciler

import (
	"context"

	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// NoopHooks is a no-op implementation of ReconcileHooks.
// Embed it in your Hooks struct to avoid implementing methods you don't need:
//
//	type MyHooks struct {
//	    reconciler.NoopHooks
//	    client client.Client
//	}
//
//	// Only override the methods you care about:
//	func (h *MyHooks) Reconcile(ctx context.Context, obj client.Object) (ctrl.Result, error) {
//	    // your logic here
//	}
type NoopHooks struct{}

func (NoopHooks) BeforeReconcile(_ context.Context, _ reconcile.Request) error {
	return nil
}

func (NoopHooks) Reconcile(_ context.Context, _ client.Object) (ctrl.Result, error) {
	return ctrl.Result{}, nil
}

func (NoopHooks) AfterReconcile(_ context.Context, _ client.Object, r ctrl.Result) (ctrl.Result, error) {
	return r, nil
}

func (NoopHooks) OnError(_ context.Context, _ client.Object, err error) (ctrl.Result, error) {
	return ctrl.Result{}, err
}
`

// appHooksTmpl is the user-owned hook stub (create-only).
const appHooksTmpl = `// Package {{ .KindLower }} contains user-owned business logic for {{ .Kind }}.
//
// This file was created by {{ .PluginKey }} and will NOT be overwritten on
// subsequent scaffold runs. It is yours to edit freely.
//
// Implement the ReconcileHooks interface from internal/platform/reconciler/hooks.go.
// The generated reconciler will call your methods in order on each reconcile cycle.
package {{ .KindLower }}

import (
	"context"

	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// Hooks implements platform/reconciler.ReconcileHooks for {{ .Kind }}.
//
// Add your dependencies (database clients, external services, etc.) as fields
// and inject them from cmd/main.go or your setup function.
type Hooks struct {
	Client client.Client
	// TODO: add your custom dependencies here
}

// BeforeReconcile is called before the main reconcile step.
// Return nil to continue; return an error to skip Reconcile and call OnError.
func (h *Hooks) BeforeReconcile(_ context.Context, _ reconcile.Request) error {
	return nil
}

// Reconcile contains your main business logic for {{ .Kind }}.
// obj is the current {{ .Kind }} object from the API server.
func (h *Hooks) Reconcile(_ context.Context, _ client.Object) (ctrl.Result, error) {
	// TODO: implement your business logic here.
	// Use h.Client to read/write Kubernetes resources.
	return ctrl.Result{}, nil
}

// AfterReconcile is called after a successful Reconcile.
// Use it to update status conditions, emit Events, etc.
func (h *Hooks) AfterReconcile(_ context.Context, _ client.Object, result ctrl.Result) (ctrl.Result, error) {
	return result, nil
}

// OnError is called when BeforeReconcile or Reconcile returns an error.
// Use it to update status conditions and decide whether to requeue.
func (h *Hooks) OnError(_ context.Context, _ client.Object, err error) (ctrl.Result, error) {
	return ctrl.Result{}, err
}
`

// appHooksTestTmpl is the user-owned hook test stub (create-only).
const appHooksTestTmpl = `// Package {{ .KindLower }} — unit tests for {{ .Kind }} hooks.
//
// This file was created by {{ .PluginKey }} and will NOT be overwritten.
// Add your test cases here.
package {{ .KindLower }}_test

import (
	"context"
	"testing"

	"sigs.k8s.io/controller-runtime/pkg/client/fake"
)

func TestHooks_Reconcile_Noop(t *testing.T) {
	fakeClient := fake.NewClientBuilder().Build()
	hooks := &{{ .Kind }}Hooks{Client: fakeClient}

	result, err := hooks.Reconcile(context.Background(), nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result.Requeue {
		t.Fatalf("unexpected requeue")
	}
}

// TODO: add test cases for your business logic
`
