/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package scaffolds

// InitData holds the data required to render init scaffold templates.
type InitData struct {
	// Domain is the API domain (e.g. "example.com").
	Domain string
	// Repo is the Go module path (e.g. "github.com/myorg/my-operator").
	Repo string
	// ProjectName is the human-readable project name.
	ProjectName string
	// PluginKey is the full plugin identifier (e.g. "decoupled-go.example.com/v1").
	PluginKey string
	// PluginVersion is the plugin semver string (e.g. "v1.0.0").
	PluginVersion string
}

// RenderInit renders all init scaffold templates and returns a map of
// path → file content ready to be added to the plugin response universe.
func RenderInit(data InitData) (map[string]string, error) {
	return renderMap(initPlatformTemplates, data)
}

// initPlatformTemplates maps destination file paths to Go text/template strings
// for the init subcommand. These are platform-zone files (always overwritten).
var initPlatformTemplates = map[string]string{
	"internal/platform/doc.go": `// Code generated by {{ .PluginKey }} ({{ .PluginVersion }}). DO NOT EDIT.
// Regenerate: kubebuilder edit --plugins {{ .PluginKey }} --regenerate
package platform
`,

	"internal/platform/manager/manager.go": `// Code generated by {{ .PluginKey }} ({{ .PluginVersion }}). DO NOT EDIT.
package manager

import (
	"flag"
	"os"

	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/healthz"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
)

// Options holds the command-line options for the manager.
type Options struct {
	MetricsAddr          string
	EnableLeaderElection bool
	ProbeAddr            string
}

// DefaultOptions returns the default manager options.
func DefaultOptions() Options {
	return Options{
		MetricsAddr:          ":8080",
		EnableLeaderElection: false,
		ProbeAddr:            ":8081",
	}
}

// BindFlags binds manager options to the provided flag set.
func (o *Options) BindFlags(fs *flag.FlagSet) {
	fs.StringVar(&o.MetricsAddr, "metrics-bind-address", o.MetricsAddr,
		"The address the metric endpoint binds to.")
	fs.StringVar(&o.ProbeAddr, "health-probe-bind-address", o.ProbeAddr,
		"The address the probe endpoint binds to.")
	fs.BoolVar(&o.EnableLeaderElection, "leader-elect", o.EnableLeaderElection,
		"Enable leader election for controller manager.")
}

// New creates a new controller manager with standard options.
func New(opts Options) (ctrl.Manager, error) {
	zapOpts := zap.Options{Development: true}
	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&zapOpts)))

	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Metrics:                metricsserver.Options{BindAddress: opts.MetricsAddr},
		HealthProbeBindAddress: opts.ProbeAddr,
		LeaderElection:         opts.EnableLeaderElection,
		LeaderElectionID:       "{{ .Domain }}.leader-election",
	})
	if err != nil {
		ctrl.Log.Error(err, "Failed to create manager")
		os.Exit(1)
	}

	if err = mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
		ctrl.Log.Error(err, "Failed to set up health check")
		os.Exit(1)
	}
	if err = mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
		ctrl.Log.Error(err, "Failed to set up ready check")
		os.Exit(1)
	}

	return mgr, nil
}
`,

	"internal/app/doc.go": `// Package app contains user-owned business logic.
// Files in this package are created once by {{ .PluginKey }} and never overwritten.
// Add your domain logic, hook implementations, and custom types here.
package app
`,

	"go.mod": `module {{ .Repo }}

go 1.21

require (
	sigs.k8s.io/controller-runtime v0.18.0
	k8s.io/apimachinery v0.31.0
	k8s.io/client-go v0.31.0
)
`,

	"Makefile": `.PHONY: generate manifests build test lint install

CONTROLLER_GEN ?= $(shell which controller-gen 2>/dev/null)

generate: ## Generate code (DeepCopy, etc.)
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."

manifests: ## Generate CRD manifests and RBAC
	$(CONTROLLER_GEN) rbac:roleName=manager-role crd webhook paths="./..." \
		output:crd:artifacts:config=config/crd/bases

build: ## Build the operator binary
	go build -o bin/manager ./cmd/

test: ## Run unit tests
	go test ./... -coverprofile cover.out

lint: ## Run linter
	golangci-lint run ./...

install: ## Install CRDs into the cluster
	kubectl apply -f config/crd/bases/
`,

	"Dockerfile": `# Code generated by {{ .PluginKey }} ({{ .PluginVersion }}). DO NOT EDIT.
# Build the manager binary
FROM golang:1.21 AS builder
ARG TARGETOS
ARG TARGETARCH
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} \
    go build -a -o manager ./cmd/

# Use distroless as minimal base image
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532
ENTRYPOINT ["/manager"]
`,

	".gitignore": `# Generated by {{ .PluginKey }}
bin/
cover.out
`,
}
