/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package scaffolds

import (
	"fmt"
	"strings"
)

// WebhookData holds the data required to render webhook scaffold templates.
type WebhookData struct {
	// Group, Version, Kind identify the resource.
	Group   string
	Version string
	Kind    string
	// Defaulting indicates a mutating webhook should be scaffolded.
	Defaulting bool
	// Validating indicates a validating webhook should be scaffolded.
	Validating bool
	// ProgrammaticValidation indicates a Go-based custom validator.
	ProgrammaticValidation bool
	// PluginKey and PluginVersion are for provenance headers.
	PluginKey     string
	PluginVersion string
}

// KindLower returns the lowercase Kind.
func (d WebhookData) KindLower() string { return strings.ToLower(d.Kind) }

// RenderWebhookPlatform renders platform-zone webhook templates (always overwritten).
func RenderWebhookPlatform(data WebhookData) (map[string]string, error) {
	rawMap := map[string]string{
		fmt.Sprintf("internal/platform/webhook/%s_webhook.go", data.KindLower()): platformWebhookTmpl,
		"internal/platform/webhook/hooks.go":                                      platformWebhookHooksTmpl,
	}
	return renderMap(rawMap, data)
}

// RenderWebhookApp renders app-zone webhook stub templates (create-only).
func RenderWebhookApp(data WebhookData) (map[string]string, error) {
	rawMap := map[string]string{
		fmt.Sprintf("internal/app/%s/webhook_hooks.go", data.KindLower()): appWebhookHooksTmpl,
	}
	return renderMap(rawMap, data)
}

const platformWebhookHooksTmpl = `// Code generated by {{ .PluginKey }} ({{ .PluginVersion }}). DO NOT EDIT.
package webhook

import (
	"context"

	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// ValidationHooks defines the extension points for {{ .Kind }} admission validation.
// Implement this interface in internal/app/{{ .KindLower }}/webhook_hooks.go.
type ValidationHooks interface {
	// ValidateCreate is called when a new {{ .Kind }} is created.
	ValidateCreate(ctx context.Context, obj runtime.Object) (admission.Warnings, error)
	// ValidateUpdate is called when an existing {{ .Kind }} is updated.
	ValidateUpdate(ctx context.Context, oldObj, newObj runtime.Object) (admission.Warnings, error)
	// ValidateDelete is called when a {{ .Kind }} is deleted.
	ValidateDelete(ctx context.Context, obj runtime.Object) (admission.Warnings, error)
}

// DefaultingHooks defines the extension points for {{ .Kind }} mutation/defaulting.
// Implement this interface in internal/app/{{ .KindLower }}/webhook_hooks.go.
type DefaultingHooks interface {
	// Default sets default values on a new or updated {{ .Kind }}.
	Default(ctx context.Context, obj runtime.Object) error
}
`

const platformWebhookTmpl = `// Code generated by {{ .PluginKey }} ({{ .PluginVersion }}). DO NOT EDIT.
// Regenerate: kubebuilder edit --plugins {{ .PluginKey }} --regenerate
package webhook

import (
	"context"

	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// {{ .Kind }}WebhookHandler wires Kubernetes admission webhooks to user-provided
// ValidationHooks and DefaultingHooks implementations.
// DO NOT EDIT — implement the interfaces in internal/app/{{ .KindLower }}/webhook_hooks.go.
type {{ .Kind }}WebhookHandler struct {
	validation ValidationHooks
	defaulting DefaultingHooks
}

// New{{ .Kind }}WebhookHandler creates a webhook handler wired to the provided hooks.
func New{{ .Kind }}WebhookHandler(v ValidationHooks, d DefaultingHooks) *{{ .Kind }}WebhookHandler {
	return &{{ .Kind }}WebhookHandler{validation: v, defaulting: d}
}
{{ if .Defaulting }}
// Default implements admission.Defaulter.
func (h *{{ .Kind }}WebhookHandler) Default(ctx context.Context, obj runtime.Object) error {
	if h.defaulting == nil {
		return nil
	}
	return h.defaulting.Default(ctx, obj)
}
{{ end }}{{ if .Validating }}
// ValidateCreate implements admission.Validator.
func (h *{{ .Kind }}WebhookHandler) ValidateCreate(ctx context.Context, obj runtime.Object) (admission.Warnings, error) {
	if h.validation == nil {
		return nil, nil
	}
	return h.validation.ValidateCreate(ctx, obj)
}

// ValidateUpdate implements admission.Validator.
func (h *{{ .Kind }}WebhookHandler) ValidateUpdate(ctx context.Context, oldObj, newObj runtime.Object) (admission.Warnings, error) {
	if h.validation == nil {
		return nil, nil
	}
	return h.validation.ValidateUpdate(ctx, oldObj, newObj)
}

// ValidateDelete implements admission.Validator.
func (h *{{ .Kind }}WebhookHandler) ValidateDelete(ctx context.Context, obj runtime.Object) (admission.Warnings, error) {
	if h.validation == nil {
		return nil, nil
	}
	return h.validation.ValidateDelete(ctx, obj)
}
{{ end }}
// SetupWebhookWithManager registers the webhook handler with the controller manager.
func (h *{{ .Kind }}WebhookHandler) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		// TODO: replace with your concrete API type.
		// For(&appsv1.{{ .Kind }}{}).
		Complete()
}
`

const appWebhookHooksTmpl = `// Package {{ .KindLower }} — user-owned webhook hooks for {{ .Kind }}.
//
// This file was created by {{ .PluginKey }} and will NOT be overwritten.
// Implement ValidationHooks and/or DefaultingHooks from
// internal/platform/webhook/hooks.go.
package {{ .KindLower }}

import (
	"context"

	"k8s.io/apimachinery/pkg/runtime"{{ if .Validating }}
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"{{ end }}
)
{{ if .Validating }}
// ValidationHooksImpl implements platform/webhook.ValidationHooks for {{ .Kind }}.
type ValidationHooksImpl struct {
	// TODO: add your dependencies here
}

func (h *ValidationHooksImpl) ValidateCreate(_ context.Context, obj runtime.Object) (admission.Warnings, error) {
	// TODO: implement create validation
	return nil, nil
}

func (h *ValidationHooksImpl) ValidateUpdate(_ context.Context, _, _ runtime.Object) (admission.Warnings, error) {
	// TODO: implement update validation
	return nil, nil
}

func (h *ValidationHooksImpl) ValidateDelete(_ context.Context, _ runtime.Object) (admission.Warnings, error) {
	// TODO: implement delete validation
	return nil, nil
}
{{ end }}{{ if .Defaulting }}
// DefaultingHooksImpl implements platform/webhook.DefaultingHooks for {{ .Kind }}.
type DefaultingHooksImpl struct {
	// TODO: add your dependencies here
}

func (h *DefaultingHooksImpl) Default(_ context.Context, obj runtime.Object) error {
	// TODO: set default values on obj
	return nil
}
{{ end }}`
