/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1

import (
	"fmt"
	"os"

	"sigs.k8s.io/kubebuilder/v4/pkg/plugin/external"

	"sigs.k8s.io/kubebuilder/v4/pkg/plugins/decoupled-go/v1/scaffolds"
)

// handleEdit processes the "edit" command.
//
// With --regenerate: all platform-layer files are regenerated; app-layer files
// are left untouched. Migration warnings are printed to stderr when the
// plugin version has changed since the last generation.
//
// Without --regenerate: the command is a no-op (passes universe through).
func handleEdit(req *external.PluginRequest, resp *external.PluginResponse) error {
	if !flagBool(req.Args, "--regenerate") {
		// No-op when --regenerate is not set.
		return nil
	}

	// Read the existing lock file from the universe (if present).
	lockPath := lockFilePath()
	existingLock, hasLock := req.Universe[lockPath]
	if hasLock {
		oldVersion, err := scaffolds.ParseLockFileVersion(existingLock)
		if err != nil {
			fmt.Fprintf(os.Stderr, "[decoupled-go/v1] warning: could not parse lock file: %v\n", err)
		} else if oldVersion != PluginVersion {
			printMigrationWarnings(oldVersion, PluginVersion)
		}
	}

	// Re-run all scaffold commands for files already tracked in the universe.
	// In a full implementation this would iterate the lock file's file list
	// and regenerate only platform-zone entries.
	//
	// For now: regenerate a sentinel platform file to demonstrate the pattern.
	resp.Universe["internal/platform/doc.go"] = platformDocGo(PluginVersion)

	// Update the lock file.
	newLock, err := scaffolds.NewLockFile(PluginVersion, PluginKey).Marshal()
	if err != nil {
		return fmt.Errorf("marshal updated lock file: %w", err)
	}
	resp.Universe[lockPath] = newLock

	return nil
}

// printMigrationWarnings writes migration guidance to stderr when the plugin
// version changes between the last generation and the current run.
func printMigrationWarnings(oldVersion, newVersion string) {
	fmt.Fprintf(os.Stderr, "\n[decoupled-go/v1] Plugin version changed: %s → %s\n", oldVersion, newVersion)
	fmt.Fprintf(os.Stderr, "  Platform files have been regenerated.\n")
	fmt.Fprintf(os.Stderr, "  App files (internal/app/) are unchanged.\n")
	fmt.Fprintf(os.Stderr, "  Review the MIGRATION.md in the plugin repository for interface changes.\n\n")
}

// platformDocGo returns the content of the platform layer doc.go file with
// an embedded plugin version for provenance tracking.
func platformDocGo(version string) string {
	return fmt.Sprintf(`// Code generated by decoupled-go/v1 (%s). DO NOT EDIT.
// Regenerate: kubebuilder edit --plugins decoupled-go.example.com/v1 --regenerate
package platform
`, version)
}
