name: Pinact
on:
  pull_request:
jobs:
  pinact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        
      - name: Install pinact
        run: |
          curl -sSfL https://raw.githubusercontent.com/suzuki-shunsuke/pinact/main/scripts/install.sh | sh -s -- -v v3.9.0
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Pin GitHub Actions
        run: |
          git diff --name-only origin/${{ github.base_ref }} HEAD \
            | grep -E 'workflows/.*\.ya?ml$' \
            | xargs pinact run --diff --check
